### ISSUE TITLE
'Could not parse for GALX token'

### ISSUE THREAD

**Issue by matthewTa127** [aaronpk/Google-Voice-PHP-API#20]
I not sure what to do to fix this

**Comment by auctionsjeff** [comment]
Steps I took to fix the same error:
1. Log the $html variable as part of the "Could not parse" error log message
2. Look in the log for the string "GALX".
3. If it's there (was for me), update the RegEx to match the new string Google's ServiceLogin endpoint is producing now (it changed recently it seems).

See [my PR](https://github.com/aaronpk/Google-Voice-PHP-API/pull/21) for how I fixed the similar (same?) issue I had.

**Comment by matthewTa127** [comment]
What are you responding to?

**Comment by jamenlang** [comment]
Google changed their html order of name/type/value to type/name/value.

if (preg_match('/type="hidden"\s*name="GALX"\s*value="([^"]+)"/', $html, $match))
                        $GALX = $match[1];
