### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by dbthinkwik** [aaronpk/Google-Voice-PHP-API#31]
Currently, i am getting below error in Google login,

>  Fatal error: Uncaught Exception: Could not log in to Google Voice with username: developer12345678901@gmail.com Look at error log for detailed input information. in /Applications/MAMP/htdocs/Google-Voice-PHP-API-master/GoogleVoice.php:75 Stack trace: #0 /Applications/MAMP/htdocs/Google-Voice-PHP-API-master/GoogleVoice.php(160): GoogleVoice->_logIn() #1 /Applications/MAMP/htdocs/Google-Voice-PHP-API-master/example.php(17): GoogleVoice->sendSMS('+XXX XXX XXXX', 'Sending a messa...') #2 {main} thrown in /Applications/MAMP/htdocs/Google-Voice-PHP-API-master/GoogleVoice.php on line 75

I tried to debug the lib and print cURL request and found "Javascript doesn't support error" 
<img width="1004" alt="Screenshot 2019-05-22 at 3 19 28 PM" src="https://user-images.githubusercontent.com/18225876/58165269-095c4200-7ca5-11e9-835d-49985ac65726.png">

however javascript is enabled in Browser. Also, two factor authentication is disabled. 

Please help me to debug the issue.

**Comment by beetjerky** [comment]
Hi. Were you ever able to find a solution to this? I'm guessing google stores whether or not js is enabled in a cookie BEFORE the actual login submission takes place. How exactly to simulate that, I'm not sure.
